language: node_js

sudo: required

node_js:
  - "6.9"
  - "7.0"
  - "7.1"
  - "7.2"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - export CXX="g++-4.8"
  - npm install 

script:
  - testrpc &
  - truffle test
